#ifndef OCPP_CHARGE_POINT_STATUS_H
#define OCPP_CHARGE_POINT_STATUS_H

#define OCPP_CP_STATUS_AVAILABLE "Available"
#define OCPP_CP_STATUS_PREPARING "Preparing"
#define OCPP_CP_STATUS_CHARGING "Charging"
#define OCPP_CP_STATUS_SUSPENDED_EVSE "SuspendedEVSE"
#define OCPP_CP_STATUS_SUSPENDED_EV "SuspendedEV"
#define OCPP_CP_STATUS_FINISHING "Finishing"
#define OCPP_CP_STATUS_RESERVED "Reserved"
#define OCPP_CP_STATUS_UNAVAILABLE "Unavailable"
#define OCPP_CP_STATUS_FAULTED "Faulted"

// See status notification table in ocpp protocol specification
enum ocpp_cp_status_id{
	eOCPP_CP_STATUS_AVAILABLE = 1,
	eOCPP_CP_STATUS_PREPARING,
	eOCPP_CP_STATUS_CHARGING,
	eOCPP_CP_STATUS_SUSPENDED_EV,
	eOCPP_CP_STATUS_SUSPENDED_EVSE,
	eOCPP_CP_STATUS_FINISHING,
	eOCPP_CP_STATUS_RESERVED,
	eOCPP_CP_STATUS_UNAVAILABLE,
	eOCPP_CP_STATUS_FAULTED,
};

#endif /*OCPP_CHARGE_POINT_STATUS_H*/
