#ifndef OCPP_CHARGE_POINT_STATUS_H
#define OCPP_CHARGE_POINT_STATUS_H

#define OCPP_CP_STATUS_AVAILABLE "Available"
#define OCPP_CP_STATUS_PREPARING "Preparing"
#define OCPP_CP_STATUS_CHARGING "Charging"
#define OCPP_CP_STATUS_SUSPENDED_EVSE "SuspendedEVSE"
#define OCPP_CP_STATUS_SUSPENDED_EV "SuspendedEV"
#define OCPP_CP_STATUS_FINISHING "Finishing"
#define OCPP_CP_STATUS_RESERVED "Reserved"
#define OCPP_CP_STATUS_UNAVAILABLE "Unavailable"
#define OCPP_CP_STATUS_FAULTED "Faulted"

#endif /*OCPP_CHARGE_POINT_STATUS_H*/
