#ifndef OCPP_AUTHORIZATION_STATUS_H
#define OCPP_AUTHORIZATION_STATUS_H

#define OCPP_AUTHORIZATION_STATUS_ACCEPTED "Accepted"
#define OCPP_AUTHORIZATION_STATUS_BLOCKED "Blocked"
#define OCPP_AUTHORIZATION_STATUS_EXPIRED "Expired"
#define OCPP_AUTHORIZATION_STATUS_INVALID "Invalid"
#define OCPP_AUTHORIZATION_STATUS_CONCURRENT_TX "ConcurrentTx"

#endif /*OCPP_AUTHORIZATION_STATUS_H*/
