#ifndef OCPP_UNLOCK_STATUS_H
#define OCPP_UNLOCK_STATUS_H

#define OCPP_UNLOCK_STATUS_UNLOCKED "Unlocked"
#define OCPP_UNLOCK_STATUS_UNLOCK_FAILED "UnlockFailed"
#define OCPP_UNLOCK_STATUS_NOT_SUPPORTED "NotSupported"

#endif /*OCPP_UNLOCK_STATUS_H*/
