#ifndef OCPP_DATA_TRANSFER_STATUS_H
#define OCPP_DATA_TRANSFER_STATUS_H

#define OCPP_DATA_TRANSFER_STATUS_ACCEPTED "Accepted"
#define OCPP_DATA_TRANSFER_STATUS_REJECTED "Rejected"
#define OCPP_DATA_TRANSFER_STATUS_UNKNOWN_MESSAGE_ID "UnknownMessageId"
#define OCPP_DATA_TRANSFER_STATUS_UNKNOWN_VENDOR_ID "UnknownVendorId"

#endif /*OCPP_DATA_TRANSFER_STATUS_H*/
