#ifndef OCPP_RESERVATION_STATUS_H
#define OCPP_RESERVATION_STATUS_H

#define OCPP_RESERVATION_STATUS_ACCEPTED "Accepted"
#define OCPP_RESERVATION_STATUS_FAULTED "Faulted"
#define OCPP_RESERVATION_STATUS_OCCUPIED "Occupied"
#define OCPP_RESERVATION_STATUS_REJECTED "Rejected"
#define OCPP_RESERVATION_STATUS_UNAVAILABLE "Unavailable"

#endif /*OCPP_RESERVATION_STATUS_H*/
