#ifndef OCPP_DIAGNOSTICS_STATUS_H
#define OCPP_DIAGNOSTICS_STATUS_H

#define OCPP_DIAGNOSTICS_STATUS_IDLE "Idle"
#define OCPP_DIAGNOSTICS_STATUS_UPLOADED "Uploaded"
#define OCPP_DIAGNOSTICS_STATUS_UPLOAD_FAILED "UploadFailed"
#define OCPP_DIAGNOSTICS_STATUS_UPLOADING "Uploading"

#endif /*OCPP_DIAGNOSTICS_STATUS_H*/
