#ifndef OCPP_REGISTRATION_STATUS_H
#define OCPP_REGISTRATION_STATUS_H

#define OCPP_REGISTRATION_ACCEPTED "Accepted"
#define OCPP_REGISTRATION_PENDING "Pending"
#define OCPP_REGISTRATION_REJECTED "Rejected"

enum ocpp_registration_status{
	eOCPP_REGISTRATION_ACCEPTED,
	eOCPP_REGISTRATION_PENDING,
	eOCPP_REGISTRATION_REJECTED
};

#endif /*OCPP_REGISTRATION_STATUS_H*/
