#ifndef OCPP_CANCEL_RESERVATION_STATUS_H
#define OCPP_CANCEL_RESERVATION_STATUS_H

#define OCPP_CANCEL_RESERVATION_STATUS_ACCEPTED "Accepted"
#define OCPP_CANCEL_RESERVATION_STATUS_REJECTED "Rejected"

#endif /*OCPP_CANCEL_RESERVATION_STATUS_H*/
