#ifndef OCPP_TRIGGER_MESSAGE_STATUS_H
#define OCPP_TRIGGER_MESSAGE_STATUS_H

#define OCPP_TRIGGER_MESSAGE_STATUS_ACCEPTED "Accepted"
#define OCPP_TRIGGER_MESSAGE_STATUS_REJECTED "Rejected"
#define OCPP_TRIGGER_MESSAGE_STATUS_NOT_IMPLEMENTED "NotImplemented"

#endif /*OCPP_TRIGGER_MESSAGE_STATUS_H*/
