#ifndef OCPP_CLEAR_CHARGING_PROFILE_STATUS_H
#define OCPP_CLEAR_CHARGING_PROFILE_STATUS_H

#define OCPP_CLEAR_CHARGING_PROFILE_STATUS_ACCEPTED "Accepted"
#define OCPP_CLEAR_CHARGING_PROFILE_STATUS_UNKNOWN "Unknown"

#endif /*OCPP_CLEAR_CHARGING_PROFILE_STATUS_H*/
