#ifndef OCPP_AVAILABILITY_STATUS_H
#define OCPP_AVAILABILITY_STATUS_H

#define OCPP_AVAILABILITY_STATUS_ACCEPTED "Accepted"
#define OCPP_AVAILABILITY_STATUS_REJECTED "Rejected"
#define OCPP_AVAILABILITY_STATUS_SCHEDULED "Scheduled"

#endif /*OCPP_AVAILABILITY_STATUS_H*/
