#ifndef OCPP_CHARGING_PROFILE_STATUS_H
#define OCPP_CHARGING_PROFILE_STATUS_H

#define OCPP_CHARGING_PROFILE_STATUS_ACCEPTED "Accepted"
#define OCPP_CHARGING_PROFILE_STATUS_REJECTED "Rejected"
#define OCPP_CHARGING_PROFILE_STATUS_NOT_SUPPORTED "NotSupported"

#endif /*OCPP_CHARGING_PROFILE_STATUS_H*/
