#ifndef OCPP_AVAILABILITY_TYPE_H
#define OCPP_AVAILABILITY_TYPE_H

#define OCPP_AVAILABILITY_TYPE_INOPERATIVE "Inoperative"
#define OCPP_AVAILABILITY_TYPE_OPERATIVE "Operative"

#endif /*OCPP_AVAILABILITY_TYPE_H*/
