#ifndef OCPP_FIRMWARE_STATUS_H
#define OCPP_FIRMWARE_STATUS_H

#define OCPP_FIRMWARE_STATUS_DOWNLOADED "Downloaded"
#define OCPP_FIRMWARE_STATUS_DOWNLOAD_FAILED "DownloadFailed"
#define OCPP_FIRMWARE_STATUS_DOWNLOADING "Downloading"
#define OCPP_FIRMWARE_STATUS_IDLE "Idle"
#define OCPP_FIRMWARE_STATUS_INSTALLATION_FAILED "InstallationFailed"
#define OCPP_FIRMWARE_STATUS_INSTALLING "Installing"
#define OCPP_FIRMWARE_STATUS_INSTALLED "Installed"

#endif /*OCPP_FIRMWARE_STATUS_H*/
