#ifndef OCPP_CONFIGURATION_STATUS_H
#define OCPP_CONFIGURATION_STATUS_H

#define OCPP_CONFIGURATION_STATUS_ACCEPTED "Accepted"
#define OCPP_CONFIGURATION_STATUS_REJECTED "Rejected"
#define OCPP_CONFIGURATION_STATUS_REBOOT_REQUIRED "RebootRequired"
#define OCPP_CONFIGURATION_STATUS_NOT_SUPPORTED "NotSupported"

#endif /*OCPP_CONFIGURATION_STATUS_H*/
