#ifndef OCPP_CLEAR_CACHE_STATUS_H
#define OCPP_CLEAR_CACHE_STATUS_H

#define OCPP_CLEAR_CACHE_STATUS_ACCEPTED "Accepted"
#define OCPP_CLEAR_CACHE_STATUS_REJECTED "Rejected"

#endif /*OCPP_CLEAR_CACHE_STATUS_H*/
