#ifndef OCPP_GET_COMPOSITE_SCHEDULE_STATUS_H
#define OCPP_GET_COMPOSITE_SCHEDULE_STATUS_H

#define OCPP_GET_COMPOSITE_SCHEDULE_STATUS_ACCEPTED "Accepted"
#define OCPP_GET_COMPOSITE_SCHEDULE_STATUS_REJECTED "Rejected"

#endif /*OCPP_GET_COMPOSITE_SCHEDULE_STATUS_H*/
