#ifndef OCPP_UPDATE_STATUS_H
#define OCPP_UPDATE_STATUS_H

#define OCPP_UPDATE_STATUS_ACCEPTED "Accepted"
#define OCPP_UPDATE_STATUS_FAILED "Failed"
#define OCPP_UPDATE_STATUS_NOTSUPPORTED "NotSupported"
#define OCPP_UPDATE_STATUS_VERSION_MISMATCH "VersionMismatch"

#endif /*OCPP_UPDATE_STATUS_H*/
