#ifndef OCPP_REMOTE_START_STOP_STATUS_H
#define OCPP_REMOTE_START_STOP_STATUS_H

#define OCPP_REMOTE_START_STOP_STATUS_ACCEPTED "Accepted"
#define OCPP_REMOTE_START_STOP_STATUS_REJECTED "Rejected"


#endif /*OCPP_REMOTE_START_STOP_STATUS_H*/
