#include "types/ocpp_key_value.h"
#include "types/ocpp_ci_string_type.h"
#include "types/ocpp_enum.h"

bool is_configuration_key(const char * key){
	return ocpp_validate_enum(key, 31,
				OCPP_CONFIG_KEY_AUTHORIZE_REMOTE_TX_REQUESTS,
				OCPP_CONFIG_KEY_CLOCK_ALIGNED_DATA_INTERVAL,
				OCPP_CONFIG_KEY_CONNECTION_TIMEOUT,
				OCPP_CONFIG_KEY_CONNECTOR_PHASE_ROTATION,
				OCPP_CONFIG_KEY_CONNECTOR_PHASE_ROTATION_MAX_LENGTH,
				OCPP_CONFIG_KEY_GET_CONFIGURATION_MAX_KEYS,
				OCPP_CONFIG_KEY_HEARTBEAT_INTERVAL,
				OCPP_CONFIG_KEY_LIGHT_INTENSITY,
				OCPP_CONFIG_KEY_LOCAL_AUTHORIZE_OFFLINE,
				OCPP_CONFIG_KEY_LOCAL_PRE_AUTHORIZE,
				OCPP_CONFIG_KEY_METER_VALUES_ALIGNED_DATA,
				OCPP_CONFIG_KEY_METER_VALUES_ALIGNED_DATA_MAX_LENGTH,
				OCPP_CONFIG_KEY_METER_VALUES_SAMPLED_DATA,
				OCPP_CONFIG_KEY_METER_VALUES_SAMPLED_DATA_MAX_LENGTH,
				OCPP_CONFIG_KEY_METER_VALUE_SAMPLE_INTERVAL,
				OCPP_CONFIG_KEY_NUMBER_OF_CONNECTORS,
				OCPP_CONFIG_KEY_RESET_RETRIES,
				OCPP_CONFIG_KEY_STOP_TRANSACTION_ON_EV_SIDE_DISCONNECT,
				OCPP_CONFIG_KEY_STOP_TRANSACTION_ON_INVALID_ID,
				OCPP_CONFIG_KEY_STOP_TXN_ALIGNED_DATA,
				OCPP_CONFIG_KEY_STOP_TXN_ALIGNED_DATA_MAX_LENGTH,
				OCPP_CONFIG_KEY_STOP_TXN_SAMPLED_DATA,
				OCPP_CONFIG_KEY_STOP_TXN_SAMPLED_DATA_MAX_LENGTH,
				OCPP_CONFIG_KEY_SUPPORTED_FEATURE_PROFILES,
				OCPP_CONFIG_KEY_SUPPORTED_FEATURE_PROFILES_MAX_LENGTH,
				OCPP_CONFIG_KEY_TRANSACTION_MESSAGE_ATTEMPTS,
				OCPP_CONFIG_KEY_TRANSACTION_MESSAGE_RETRY_INTERVAL,
				OCPP_CONFIG_KEY_UNLOCK_CONNECTOR_ON_EV_SIDE_DISCONNECT,
				OCPP_CONFIG_KEY_LOCAL_AUTH_LIST_ENABLED,
				OCPP_CONFIG_KEY_LOCAL_AUTH_LIST_MAX_LENGTH,
				OCPP_CONFIG_KEY_SEND_LOCAL_LIST_MAX_LENGTH) == 0;
}
cJSON * create_key_value_json(struct ocpp_key_value key_value){
	if(!is_ci_string_type(key_value.key, 50))
		return NULL;

	if(!is_ci_string_type(key_value.value, 500))
		return NULL;

	cJSON * result = cJSON_CreateObject();
	if(result == NULL)
		return NULL;

	cJSON * key_json = cJSON_CreateString(key_value.key);
	if(key_json == NULL){
		goto error;
	}
	cJSON_AddItemToObject(result, "key", key_json);

	cJSON_AddBoolToObject(result, "readonly", key_value.readonly);

	cJSON * value_json = cJSON_CreateString(key_value.value);
	if(value_json == NULL){
		goto error;
	}
	cJSON_AddItemToObject(result, "value", value_json);

	return result;
error:
	cJSON_Delete(result);
	return NULL;
}
