/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "mid_session.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MID_SESSION_ID, mid_session_id_t, AUTO)


PB_BIND(MID_SESSION_AUTH, mid_session_auth_t, AUTO)


PB_BIND(MID_SESSION_VERSION, mid_session_version_t, AUTO)


PB_BIND(MID_SESSION_METER_VALUE, mid_session_meter_value_t, AUTO)


PB_BIND(MID_SESSION_RECORD, mid_session_record_t, AUTO)






