/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "calibration-message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CalibrationUdpMessage, CalibrationUdpMessage, AUTO)


PB_BIND(CalibrationUdpMessage_StateMessage, CalibrationUdpMessage_StateMessage, AUTO)


PB_BIND(CalibrationUdpMessage_StateMessage_CalibrationRunMessage, CalibrationUdpMessage_StateMessage_CalibrationRunMessage, AUTO)


PB_BIND(CalibrationUdpMessage_StateMessage_VerificationState, CalibrationUdpMessage_StateMessage_VerificationState, AUTO)


PB_BIND(CalibrationUdpMessage_DataMessage, CalibrationUdpMessage_DataMessage, AUTO)


PB_BIND(CalibrationUdpMessage_DataMessage_PhaseSnapshot, CalibrationUdpMessage_DataMessage_PhaseSnapshot, AUTO)


PB_BIND(CalibrationUdpMessage_DataMessage_EnergySnapshot, CalibrationUdpMessage_DataMessage_EnergySnapshot, AUTO)


PB_BIND(CalibrationUdpMessage_ChargerAck, CalibrationUdpMessage_ChargerAck, AUTO)


PB_BIND(ChargerStateUdpMessage, ChargerStateUdpMessage, AUTO)


PB_BIND(ChargerStateUdpMessage_InitStatus, ChargerStateUdpMessage_InitStatus, AUTO)


PB_BIND(ChargerStateUdpMessage_StatusMessage, ChargerStateUdpMessage_StatusMessage, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

