name: Build 

on: push

permissions:
  id-token: write
  contents: write

env:
  GITHUB_APP_ID: "195169"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Get install token
      id: my-app
      uses: getsentry/action-github-app-token@v2
      with:
        app_id: ${{ env.GITHUB_APP_ID }}
        private_key: ${{ secrets.ZAPTEC_GIT_CONTENTS_APP_PRIVATE_KEY }}

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ steps.my-app.outputs.token }}
        submodules: recursive

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        # We've agreed on tag v5.1.1 so don't change this :)
        esp_idf_version: v5.1.1
        target: esp32
