name: Build 

on:
  push:
    tags:
      - "*"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        # We've agreed on tag v5.1.1 so don't change this :)
        esp_idf_version: v5.1.1
        target: esp32
